# Generated by Django 5.2.7 on 2026-02-21 18:03

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='workspace',
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='HackAPI.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='HackAPI.feature'),
        ),
    ]
